version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: thanhnguyen
      POSTGRES_PASSWORD: thanhdeptrai
      POSTGRES_DB: tu-ecommerce
    volumes:
     - postgres:/var/lib/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nvthanh1804@gmail.com
      PGADMIN_DEFAULT_PASSWORD: thanh
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "9999:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres
  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redis:/var/lib/redis
    restart: unless-stopped
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis: